-- Run this in the Supabase SQL editor for your project.
-- Single-user app, no auth: RLS is enabled but the policy allows all
-- operations since every request comes from the browser with the
-- publishable (anon) key.
--
-- The `books` table already exists in this project (created outside this
-- repo) with just `id` (integer identity), `title`, and `completed`. These
-- statements are additive/idempotent so they can be run against that table
-- without dropping it or losing existing rows.

create table if not exists books (
  id bigint generated by default as identity primary key,
  title text not null,
  completed boolean not null default false
);

alter table books add column if not exists author text;
alter table books add column if not exists comment text;
alter table books add column if not exists started_at date;
alter table books add column if not exists created_at timestamptz not null default now();

alter table books enable row level security;

drop policy if exists "Allow all access to books" on books;
create policy "Allow all access to books"
  on books
  for all
  using (true)
  with check (true);
